@preconcurrency import Foundation
import Crypto

/**
 Reference-typed home for an account's Ed25519 signing key.

 The key is stored as a `Curve25519.Signing.PrivateKey`, never as a `Data` copy of the seed. A
 `Data` copy is copy-on-write: handing the value out - to the signer, to the mnemonic encoder -
 spawns buffers a `memset` in this module can never reach, so the previous container's zeroing
 was defeated by design. The key type keeps the seed in the cryptography library's own storage:
 swift-crypto's `SecureBytes` on Linux, which overwrites itself on deallocation, and CryptoKit's
 storage on Apple platforms, which Apple documents as overwriting sensitive data during
 deallocation. Neither is a security boundary - see SECURITY.md - but neither leaks copies.

 Reference-typed so that copying an `Account` shares one key rather than minting more of them.

 `@unchecked Sendable` because swift-crypto declares no `Sendable` conformance for the key type on
 every platform this package builds for. It is justified narrowly: `key` is a `let`, and every
 operation performed on it - `signature(for:)`, `publicKey`, `rawRepresentation` - is
 non-mutating and touches no shared state in either backend.
 */
private final class SigningKeyBox: @unchecked Sendable {
    let key: Curve25519.Signing.PrivateKey

    init(_ key: Curve25519.Signing.PrivateKey) {
        self.key = key
    }
}

/// Represents an Algorand account with a key pair
public struct Account: Sendable {
    /// The size of an Ed25519 seed, in bytes.
    private static let privateKeyByteCount = 32

    /// The account's address
    public let address: Address

    /// The signing key - never exposed, and materialised as bytes only by ``mnemonic()``
    private let signingKey: SigningKeyBox

    /// The public key (32 bytes)
    public let publicKey: Data

    /**
     Creates a new random account

     The key is generated by `Curve25519.Signing.PrivateKey()`, which draws from the platform's
     cryptographic random source straight into the key's own storage, so no `Data` copy of the
     seed is ever made.

     - Throws: `AlgorandError.invalidAddress` if the public key does not form an address, which
       cannot happen for a well-formed key
     */
    public init() throws {
        try self.init(signingKey: Curve25519.Signing.PrivateKey())
    }

    /**
     Creates an account from a mnemonic

     - Parameter mnemonic: The 25-word mnemonic
     - Throws: `AlgorandError.invalidMnemonic` if the mnemonic is invalid or non-canonical
     */
    public init(mnemonic: String) throws {
        let seed = try Mnemonic.decode(mnemonic)
        try self.init(privateKey: seed)
    }

    /**
     Creates an account from a private key

     - Parameter privateKey: The 32-byte private key
     - Throws: `AlgorandError.encodingError` if the key is invalid
     */
    public init(privateKey: Data) throws {
        guard privateKey.count == Self.privateKeyByteCount else {
            throw AlgorandError.encodingError("Private key must be \(Self.privateKeyByteCount) bytes")
        }

        let key: Curve25519.Signing.PrivateKey
        do {
            key = try Curve25519.Signing.PrivateKey(rawRepresentation: privateKey)
        } catch {
            throw AlgorandError.encodingError("Failed to create Ed25519 signing key from private key")
        }

        try self.init(signingKey: key)
    }

    /// The designated path: derive the public key and address from the signing key.
    private init(signingKey key: Curve25519.Signing.PrivateKey) throws {
        let publicKeyData = key.publicKey.rawRepresentation
        self.signingKey = SigningKeyBox(key)
        self.publicKey = publicKeyData
        self.address = try Address(bytes: publicKeyData)
    }

    /**
     The account's mnemonic

     This is the one operation that materialises the seed as bytes, because the mnemonic is the
     seed in another alphabet. Treat the result as key material: do not log it or persist it in
     plaintext, and let it go out of scope promptly.

     - Throws: `AlgorandError.encodingError` if encoding fails
     */
    public func mnemonic() throws -> String {
        // The `Data` that `rawRepresentation` returns may alias the key's own storage on some
        // platforms, so it is deliberately not scrubbed here: overwriting it would destroy the key.
        try Mnemonic.encode(signingKey.key.rawRepresentation)
    }

    /**
     Signs data with the account's private key

     - Parameter data: The data to sign
     - Returns: The signature (64 bytes)
     - Throws: `AlgorandError.encodingError` if the Ed25519 backend fails
     */
    public func sign(_ data: Data) throws -> Data {
        do {
            return Data(try signingKey.key.signature(for: data))
        } catch {
            throw AlgorandError.encodingError("Ed25519 signing failed: \(error)")
        }
    }

    /**
     Verifies a signature

     - Parameters:
       - signature: The signature to verify
       - data: The data that was signed
     - Returns: `true` if the signature is valid
     */
    public func verify(signature: Data, for data: Data) -> Bool {
        signingKey.key.publicKey.isValidSignature(signature, for: data)
    }
}

// MARK: - CustomStringConvertible

extension Account: CustomStringConvertible {
    public var description: String {
        address.description
    }
}
