@preconcurrency import Foundation
import Testing
@testable import Algorand

/**
 Golden-vector conformance suite for the canonical MessagePack encoder.

 Every assertion in this file is BYTE EQUALITY against a hex literal, plus the
 transaction ID that the network computes from those bytes. That is the whole
 point: the pre-existing encoding tests assert only `encoded.count > 0` or that
 some substring is present, which cannot distinguish a correct encoder from a
 differently-wrong one.

 ## Where the expected bytes come from

 The vectors were generated by a script that implements go-algorand's
 msgp-generated marshalling semantics directly -- `_struct codec:",omitempty,
 omitemptyarray"`, meaning every field is dropped when it holds its zero value
 -- and then cross-checked byte-for-byte against py-algorand-sdk 2.12.0 (MIT).
 go-algorand v5.0.1-stable is the authority where the two disagree; the three
 places they do disagree are documented on the individual tests.

 No fixture file was copied from any Algorand repository. py-algorand-sdk
 vendors post-quantum fixtures under `tests/unit_tests/pq_test_data/`, but
 `lsig_address_kat.json` originates in `algorandfoundation/falcon-signatures`
 (AGPL-3.0) and the `pq*.json` files originate in
 `algorandfoundation/algokit-polytest`, which publishes no licence at all.
 Neither is safe to port into an MIT package, so the post-quantum vectors here
 are regenerated from first principles.

 ## Fixtures

 Accounts are derived deterministically from fixed labels, so the vectors can
 be regenerated at any time. The network parameters are TestNet's real genesis
 ID and hash.
 */

/// Requirement evidence: REQ-algorand-002, REQ-algorand-006, REQ-algorand-007, REQ-algorand-013, REQ-algorand-014, REQ-algorand-015, REQ-algorand-016, REQ-algorand-017, REQ-algorand-018.
@Suite
internal struct CanonicalEncodingTests {

    // MARK: - Fixtures
    internal static let genesisID = "testnet-v1.0"
    internal static let genesisHashHex = "4863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22"

    internal static let assetID: UInt64 = 31566704
    internal static let appID: UInt64 = 1284326447
    internal static let foreignApp1: UInt64 = 987654321
    internal static let foreignApp2: UInt64 = 123456789

    internal static let votePKHex = "e91da3b91e69b1a1c999b7988784c0d29bcd7b9f8e33a8789fd989aaf1a4b1d3"
    internal static let selectionPKHex = "ac2b05329c2c822e32d142d01d19ae43d0961ca36db6034a39b78e878e2fe980"
    internal static let stateProofPKHex =
        "84daf438b42604262e38933ae0a2c9ff40e3c134d5df02d244fe0de69fde1f2db7adf932ebe07ba533dd37ebce47206b" +
        "015c595059e42e5b5134151493e63066"
    internal static let metadataHashHex = "8f0c14dcbc96efd58124035f15d26a9db65df373abff1b1c6abba9823961a531"
    internal static let noteHelloHex = "68656c6c6f2073776966742d616c676f72616e64"
    internal static let leaseNonZeroHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"
    internal static let approvalProgramHex = "0a8101"
    internal static let clearStateProgramHex = "0a8101"

    // MARK: - Deferred workstreams

    /// Whether the Ed25519 backend derives its signing nonce deterministically (RFC 8032). True for
    /// swift-crypto's BoringSSL backend on Linux and Windows; false for CryptoKit on Darwin, which
    /// randomizes the nonce. Gates the byte-exact signed-envelope vector.
    internal static var ed25519SignaturesAreDeterministic: Bool {
        #if canImport(Darwin)
        return false
        #else
        return true
        #endif
    }

    internal static func genesisHash() throws -> Data {
        try hexData(genesisHashHex)
    }

    internal static func accountA() throws -> Address {
        try Address(string: "2TVXIFN4ALYYL4BS2QF5RYBCMBOXZPW3734FA6JQMUUR4FI5YSLGIQWKAY")
    }

    internal static func accountB() throws -> Address {
        try Address(string: "QSC3D2JBVUCKCRCZAUH5D2533Y4BQMYY5C5PDFQ46JDDRNWC3HQC5ZN5TQ")
    }

    internal static func accountC() throws -> Address {
        try Address(string: "PXFN3PAXKPPOGGMTCTEMNGJK4WIRWVZ5OKIZBTBGN5ANCU5J32AU6HO2RM")
    }

    internal static func authAccount() throws -> Address {
        try Address(string: "B5L4CCZGW4UXCIAGVVQ5GXWKMETZFGQF3WETB3KZ2VBVW6VJGYT7P5EXJY")
    }

    // Decoded on demand. Swift 6 strict concurrency forbids mutable statics, and a throwing
    // accessor keeps every test body free of force-unwrapping.
    internal static func votePK() throws -> Data { try hexData(votePKHex) }
    internal static func selectionPK() throws -> Data { try hexData(selectionPKHex) }
    internal static func stateProofPK() throws -> Data { try hexData(stateProofPKHex) }
    internal static func metadataHash() throws -> Data { try hexData(metadataHashHex) }
    internal static func noteHello() throws -> Data { try hexData(noteHelloHex) }
    internal static func leaseNonZero() throws -> Data { try hexData(leaseNonZeroHex) }
    internal static func approvalProgram() throws -> Data { try hexData(approvalProgramHex) }
    internal static func clearStateProgram() throws -> Data { try hexData(clearStateProgramHex) }

    // MARK: - Assertions

    /// Asserts that a transaction encodes to exactly `encodesTo` and hashes to exactly `txID`.
    /// Failures are attributed to the calling test through `sourceLocation`.
    internal func assertCanonical(
        _ transaction: any Transaction,
        groupID: Data? = nil,
        encodesTo expectedHex: String,
        txID expectedTxID: String,
        sourceLocation: SourceLocation = #_sourceLocation
    ) throws {
        let encoded = try transaction.encode(groupID: groupID)
        #expect(
            encoded.hexString == expectedHex,
            "canonical msgpack bytes differ from the golden vector",
            sourceLocation: sourceLocation
        )
        #expect(
            Self.transactionID(forEncoded: encoded) == expectedTxID,
            "transaction ID differs from the golden vector",
            sourceLocation: sourceLocation
        )
    }

    /// Computes a transaction ID the way the network does: base32(SHA512-256("TX" + encoded)).
    internal static func transactionID(forEncoded encoded: Data) -> String {
        let prefixed = Data("TX".utf8) + encoded
        return SHA512_256.hash(data: prefixed).base32EncodedString()
    }

    // MARK: - Payment

    /// Baseline payment: every header field populated, no optional fields.
    @Test
    internal func testPayNormal() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(1_000_000),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a3616d74ce000f4240a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b5" +
            "18a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3726376c4208485b1e921" +
            "ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a3736e64c420d4eb7415bc02f185f032d40bd8" +
            "e022605d7cbedbfef850793065291e151dc496a474797065a3706179",
            txID: "O5CHKYIB3T7YBA4KATYKNGWU5AB3NTN2TZ2E2IJUIZXRMNPINM2Q"
        )
    }

    /// fee=0 MUST be omitted (go-algorand omitempty). Legal: fee is paid by another txn in the group, or the sender
    /// is exempt.
    @Test
    internal func testPayFeeZero() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(1_000_000),
            fee: MicroAlgos(0),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "88a3616d74ce000f4240a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810" +
            "f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3726376c4208485b1e921ad04a14459050f" +
            "d1ebbbde38183318e8baf1961cf24638b6c2d9e0a3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedb" +
            "fef850793065291e151dc496a474797065a3706179",
            txID: "FHWLA26TH2M6ZPR3PN4T23R6H3WIHGNFTHZVOFFJAND2JQYUBL6Q"
        )
    }

    /// fv=0 MUST be omitted.
    @Test
    internal func testPayFirstValidZero() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(1_000_000),
            fee: MicroAlgos(1000),
            firstValid: 0,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "88a3616d74ce000f4240a3666565cd03e8a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c8" +
            "4ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3726376c4208485b1e921ad04a144" +
            "59050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a3736e64c420d4eb7415bc02f185f032d40bd8e022605d" +
            "7cbedbfef850793065291e151dc496a474797065a3706179",
            txID: "NBHL73LGAGG372IKJOQQGZFHUCGPXTPIZZJ5SJSGBQ72SZ3TE4QQ"
        )
    }

    /// An explicitly-supplied but empty note MUST be omitted.
    @Test
    internal func testPayEmptyNote() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(1_000_000),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash,
            note: Data()
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a3616d74ce000f4240a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b5" +
            "18a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3726376c4208485b1e921" +
            "ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a3736e64c420d4eb7415bc02f185f032d40bd8" +
            "e022605d7cbedbfef850793065291e151dc496a474797065a3706179",
            txID: "O5CHKYIB3T7YBA4KATYKNGWU5AB3NTN2TZ2E2IJUIZXRMNPINM2Q"
        )
    }

    /// An all-zero 32-byte lease MUST be omitted: go-algorand's Lease is a [32]byte and msgp omits the zero array.
    @Test
    internal func testPayZeroLease() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(1_000_000),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash,
            lease: Data(repeating: 0, count: 32)
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a3616d74ce000f4240a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b5" +
            "18a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3726376c4208485b1e921" +
            "ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a3736e64c420d4eb7415bc02f185f032d40bd8" +
            "e022605d7cbedbfef850793065291e151dc496a474797065a3706179",
            txID: "O5CHKYIB3T7YBA4KATYKNGWU5AB3NTN2TZ2E2IJUIZXRMNPINM2Q"
        )
    }

    /// gen="" MUST be omitted.
    @Test
    internal func testPayEmptyGenesisId() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(1_000_000),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: "",
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "88a3616d74ce000f4240a3666565cd03e8a2667633a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059" +
            "a7ac20dec62f7f70e5093a22a26c76cd041ba3726376c4208485b1e921ad04a14459050fd1ebbbde38183318e8ba" +
            "f1961cf24638b6c2d9e0a3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151d" +
            "c496a474797065a3706179",
            txID: "YJCXY5ZM3BDKEVBBIKBPSV6PVKDGKH2VSMMITBKHNIODR6W54ATA"
        )
    }

    /// amt=0 MUST be omitted (already handled correctly by the SDK; guards against regression).
    @Test
    internal func testPayZeroAmount() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(0),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "88a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d" +
            "4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3726376c4208485b1e921ad04a14459050fd1eb" +
            "bbde38183318e8baf1961cf24638b6c2d9e0a3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef8" +
            "50793065291e151dc496a474797065a3706179",
            txID: "47C7BMI7M33SGZ573UFCMKV2JBR5MFMDV6YYROEZAZW4KEFXFA2A"
        )
    }

    /// The compound worst case: fee=0, fv=0, gen='', note=b'', lease=zeros, amt=0. Only lv/gh/rcv/snd/type survive.
    @Test
    internal func testPayAllOmittableZero() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(0),
            fee: MicroAlgos(0),
            firstValid: 0,
            lastValid: 1051,
            genesisID: "",
            genesisHash: genesisHash,
            note: Data(),
            lease: Data(repeating: 0, count: 32)
        )

        try assertCanonical(
            transaction,
            encodesTo: "85a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba372" +
            "6376c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a3736e64c420d4eb7415" +
            "bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a3706179",
            txID: "EXDO6R246H2XMEDNGZUYA7TTDX4TQLPSKVZTREOXJHCGN4RCJ5HA"
        )
    }

    /// close field present.
    @Test
    internal func testPayCloseRemainderTo() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(1_000_000),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash,
            closeRemainderTo: try Self.accountC()
        )

        try assertCanonical(
            transaction,
            encodesTo: "8aa3616d74ce000f4240a5636c6f7365c4207dcaddbc1753dee3199314c8c6992ae5911b573d729190cc266f40d1" +
            "53a9de81a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec8" +
            "10f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3726376c4208485b1e921ad04a1445905" +
            "0fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbe" +
            "dbfef850793065291e151dc496a474797065a3706179",
            txID: "CYJK7GZCADVTX75HFNZ6WSAG5FLLL6PQ3PG7CKJ2SIUK3LJA5OUA"
        )
    }

    /// rekey field present.
    @Test
    internal func testPayRekeyTo() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(1_000_000),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash,
            rekeyTo: try Self.accountC()
        )

        try assertCanonical(
            transaction,
            encodesTo: "8aa3616d74ce000f4240a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b5" +
            "18a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3726376c4208485b1e921" +
            "ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a572656b6579c4207dcaddbc1753dee3199314" +
            "c8c6992ae5911b573d729190cc266f40d153a9de81a3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbe" +
            "dbfef850793065291e151dc496a474797065a3706179",
            txID: "RFGORNQ33632ZJ2VIJKGO2KGXWFUPCZORX2WTDVV756WIOKVB5AA"
        )
    }

    /// Every optional field populated at once: note, non-zero lease, close, rekey. Exercises canonical key ordering
    /// across the full key set.
    @Test
    internal func testPayFull() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(42),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash,
            note: try Self.noteHello(),
            lease: try Self.leaseNonZero(),
            rekeyTo: try Self.accountC(),
            closeRemainderTo: try Self.accountC()
        )

        try assertCanonical(
            transaction,
            encodesTo: "8da3616d742aa5636c6f7365c4207dcaddbc1753dee3199314c8c6992ae5911b573d729190cc266f40d153a9de81" +
            "a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f" +
            "1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba26c78c4200102030405060708090a0b0c0d0e0f10" +
            "1112131415161718191a1b1c1d1e1f20a46e6f7465c41468656c6c6f2073776966742d616c676f72616e64a37263" +
            "76c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a572656b6579c4207dcadd" +
            "bc1753dee3199314c8c6992ae5911b573d729190cc266f40d153a9de81a3736e64c420d4eb7415bc02f185f032d4" +
            "0bd8e022605d7cbedbfef850793065291e151dc496a474797065a3706179",
            txID: "TB7XWKSYGOMLW6C37RVJZTT4J3AWPT2INT6WT3RKRP3QRUU2BNDA"
        )
    }

    /// fee above 0xFFFFFFFF forces a msgpack uint64 (0xCF) width.
    @Test
    internal func testPayLargeFeeUint64() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(0xFFFF_FFFF_FFFF_FFFF),
            fee: MicroAlgos(0x1_0000_0000),
            firstValid: 0x1_0000_0000,
            lastValid: 0x1_0000_03E8,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a3616d74cfffffffffffffffffa3666565cf0000000100000000a26676cf0000000100000000a367656eac7465" +
            "73746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a" +
            "22a26c76cf00000001000003e8a3726376c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf246" +
            "38b6c2d9e0a3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a47479" +
            "7065a3706179",
            txID: "AMMKNSTBGTDVR3QQZQTLNFFIOUO56LWTMC3YYVITH4P4MWG5O6TA"
        )
    }

    // MARK: - KeyRegistration

    /// Online key registration with a state-proof key.
    @Test
    internal func testKeyregOnline() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = KeyRegistrationTransaction.online(
            sender: try Self.accountA(),
            votePK: try Self.votePK(),
            selectionPK: try Self.selectionPK(),
            voteFirst: 1000,
            voteLast: 2000,
            voteKeyDilution: 10,
            stateProofPK: try Self.stateProofPK(),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "8da3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d" +
            "4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba673656c6b6579c420ac2b05329c2c822e32d142" +
            "d01d19ae43d0961ca36db6034a39b78e878e2fe980a3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbe" +
            "dbfef850793065291e151dc496a7737072666b6579c44084daf438b42604262e38933ae0a2c9ff40e3c134d5df02" +
            "d244fe0de69fde1f2db7adf932ebe07ba533dd37ebce47206b015c595059e42e5b5134151493e63066a474797065" +
            "a66b6579726567a7766f7465667374cd03e8a6766f74656b640aa7766f74656b6579c420e91da3b91e69b1a1c999" +
            "b7988784c0d29bcd7b9f8e33a8789fd989aaf1a4b1d3a7766f74656c7374cd07d0",
            txID: "TONDNOVA6W4NX3PORCSFZTBDGQPN4U56M2QKSY5WVP3XQTP6TFQA"
        )
    }

    /// Offline key registration: no participation keys, no nonpart flag.
    @Test
    internal func testKeyregOffline() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = KeyRegistrationTransaction.offline(
            sender: try Self.accountA(),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "87a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d" +
            "4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8e0" +
            "22605d7cbedbfef850793065291e151dc496a474797065a66b6579726567",
            txID: "GR4Y6UYGMXOXEZAFALZ5X72LOPT4LTY64UO5QERCD7XITBGOHHAQ"
        )
    }

    /// NONPART. go-algorand's msgp-generated marshaller writes `nonpart` as a msgpack BOOL (0xC3), omitted when
    /// false. Emitting uint 1 (0x01) is NOT a decode error — the codec silently coerces it to `true`. The node
    /// rejects because it re-encodes canonically before verifying, so a signature made over the uint form does not
    /// match. Confirmed on TestNet: uint 1 returns HTTP 400 "At least one signature didn't pass verification",
    /// while signing canonical bytes and transmitting the uint form returns HTTP 200. The defect is the signing
    /// preimage, not the wire type.
    @Test
    internal func testKeyregNonparticipating() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = KeyRegistrationTransaction.nonparticipating(
            sender: try Self.accountA(),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "88a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d" +
            "4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba76e6f6e70617274c3a3736e64c420d4eb7415bc" +
            "02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a66b6579726567",
            txID: "5DMI7MV5AKGYEZ5B46HX7PLULHSSRFV5A6RRF4BPYBX3RR22AIVQ"
        )
    }

    /// Online key registration without a state-proof key (pre-v31 shape).
    @Test
    internal func testKeyregOnlineNoStateproof() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = KeyRegistrationTransaction.online(
            sender: try Self.accountA(),
            votePK: try Self.votePK(),
            selectionPK: try Self.selectionPK(),
            voteFirst: 1000,
            voteLast: 2000,
            voteKeyDilution: 10,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "8ca3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d" +
            "4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba673656c6b6579c420ac2b05329c2c822e32d142" +
            "d01d19ae43d0961ca36db6034a39b78e878e2fe980a3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbe" +
            "dbfef850793065291e151dc496a474797065a66b6579726567a7766f7465667374cd03e8a6766f74656b640aa776" +
            "6f74656b6579c420e91da3b91e69b1a1c999b7988784c0d29bcd7b9f8e33a8789fd989aaf1a4b1d3a7766f74656c" +
            "7374cd07d0",
            txID: "57I6JAJXHTXBMFN7O3YDNIZX6JHTDQBYJOTULL6REQTXGQ4NDZIQ"
        )
    }

    // MARK: - AssetTransfer

    /// Asset opt-in: amount 0 (omitted), receiver == sender.
    @Test
    internal func testAxferOptIn() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = AssetOptInTransaction(
            sender: try Self.accountA(),
            assetID: Self.assetID,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a461726376c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a3666565cd03" +
            "e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f0" +
            "59a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfe" +
            "f850793065291e151dc496a474797065a56178666572a478616964ce01e1ab70",
            txID: "BL2PZLX6QXHZIHM3OWIYROTEXRNEVI2JQEYMIPQGOSLEDEE73YCQ"
        )
    }

    /// Ordinary asset transfer.
    @Test
    internal func testAxferTransfer() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = AssetTransferTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            assetID: Self.assetID,
            amount: 12345,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "8aa461616d74cd3039a461726376c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2" +
            "d9e0a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f2" +
            "2d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8" +
            "e022605d7cbedbfef850793065291e151dc496a474797065a56178666572a478616964ce01e1ab70",
            txID: "YGU53J3L3PK6GK5HDE6GS2G23IKEZQURYEIITETPE3MILE3CUN2A"
        )
    }

    /// Asset close-out: aclose present, aamt zero and therefore omitted.
    @Test
    internal func testAxferCloseTo() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = AssetTransferTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            assetID: Self.assetID,
            amount: 0,
            closeRemainderTo: try Self.accountB(),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "8aa661636c6f7365c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a4617263" +
            "76c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a3666565cd03e8a2667633" +
            "a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20de" +
            "c62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065" +
            "291e151dc496a474797065a56178666572a478616964ce01e1ab70",
            txID: "ND62ROLUVB2GZVEMSIH3YTTQTVH5ORODHLHJTIEQ5UWLIQ3NQUIQ"
        )
    }

    /// Clawback: asnd is the address funds are pulled from.
    @Test
    internal func testAxferClawback() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = AssetClawbackTransaction(
            sender: try Self.accountA(),
            assetID: Self.assetID,
            assetSender: try Self.accountB(),
            assetReceiver: try Self.accountC(),
            amount: 7,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "8ba461616d7407a461726376c4207dcaddbc1753dee3199314c8c6992ae5911b573d729190cc266f40d153a9de81" +
            "a461736e64c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a3666565cd03e8" +
            "a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059" +
            "a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef8" +
            "50793065291e151dc496a474797065a56178666572a478616964ce01e1ab70",
            txID: "RGYJZXWYJKWFRLZEPRR2XCQPVX7ELPTEMCJYL7PMG55HPHKSUQ5Q"
        )
    }

    /// xaid=0 MUST be omitted. (An axfer with asset 0 is invalid on chain, but the encoder must not special-case:
    /// omitempty is uniform.)
    @Test
    internal func testAxferZeroAssetId() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = AssetTransferTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            assetID: 0,
            amount: 5,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a461616d7405a461726376c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0" +
            "a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f" +
            "1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8e022" +
            "605d7cbedbfef850793065291e151dc496a474797065a56178666572",
            txID: "7KGKHBYR52K3VZY2WQC65EKJ5W3H2IDTFMTGAULBGWJUMURVWYVA"
        )
    }

    // MARK: - AssetConfiguration

    /// Asset creation with only `total` set: apar carries a single key.
    @Test
    internal func testAcfgCreateMinimal() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = AssetCreateTransaction(
            sender: try Self.accountA(),
            assetParams: AssetParams(total: 1000),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "88a46170617281a174cd03e8a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c42048" +
            "63b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb74" +
            "15bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a461636667",
            txID: "AJWRNFTBZAYDH3IKUWV4R4G6MAQUKTOW2S3IWHDBYXJF26WHULTA"
        )
    }

    /// Asset creation with every apar field: total, decimals, default-frozen, unit name, asset name, url, metadata
    /// hash and all four role addresses.
    @Test
    internal func testAcfgCreateFull() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = AssetCreateTransaction(
            sender: try Self.accountA(),
            assetParams: AssetParams(
                total: 10_000_000,
                decimals: 6,
                defaultFrozen: true,
                unitName: "SWFT",
                assetName: "Swift Algorand Token",
                url: "https://example.invalid/swft",
                metadataHash: try Self.metadataHash(),
                manager: try Self.accountA(),
                reserve: try Self.accountB(),
                freeze: try Self.accountC(),
                clawback: try Self.accountA()
            ),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "88a4617061728ba2616dc4208f0c14dcbc96efd58124035f15d26a9db65df373abff1b1c6abba9823961a531a261" +
            "6eb4537769667420416c676f72616e6420546f6b656ea26175bc68747470733a2f2f6578616d706c652e696e7661" +
            "6c69642f73776674a163c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a264" +
            "6306a26466c3a166c4207dcaddbc1753dee3199314c8c6992ae5911b573d729190cc266f40d153a9de81a16dc420" +
            "d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a172c4208485b1e921ad04a14459" +
            "050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a174ce00989680a2756ea453574654a3666565cd03e8a266" +
            "7633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac" +
            "20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef85079" +
            "3065291e151dc496a474797065a461636667",
            txID: "YOAQZYEMJFNDQPTZWDCKDMULB6LKCTHBMF5BFVJFGDOYCKXOWBMQ"
        )
    }

    /// default_frozen=False MUST be omitted, not emitted as msgpack false.
    @Test
    internal func testAcfgCreateDefaultFrozenFalse() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = AssetCreateTransaction(
            sender: try Self.accountA(),
            assetParams: AssetParams(
                total: 500,
                decimals: 2,
                defaultFrozen: false,
                unitName: "NF"
            ),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "88a46170617283a2646302a174cd01f4a2756ea24e46a3666565cd03e8a2667633a367656eac746573746e65742d" +
            "76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd04" +
            "1ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a461" +
            "636667",
            txID: "LZYWVF5CYJTEI2HQYCQ5MAVZT4WNIQFB7XQDJWCMRA2X732D3KYA"
        )
    }

    /// Asset reconfiguration: caid set, apar carries the new role addresses.
    @Test
    internal func testAcfgReconfigure() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = AssetConfigTransaction.update(
            sender: try Self.accountA(),
            assetID: Self.assetID,
            manager: try Self.accountB(),
            reserve: try Self.accountB(),
            freeze: try Self.accountC(),
            clawback: try Self.accountC(),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a46170617284a163c4207dcaddbc1753dee3199314c8c6992ae5911b573d729190cc266f40d153a9de81a166c4" +
            "207dcaddbc1753dee3199314c8c6992ae5911b573d729190cc266f40d153a9de81a16dc4208485b1e921ad04a144" +
            "59050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a172c4208485b1e921ad04a14459050fd1ebbbde381833" +
            "18e8baf1961cf24638b6c2d9e0a463616964ce01e1ab70a3666565cd03e8a2667633a367656eac746573746e6574" +
            "2d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd" +
            "041ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a4" +
            "61636667",
            txID: "FIP37JJ54CIANYKMVYH32OW4VVAKSFY72YXTWRLTILJ47YSJ7WJA"
        )
    }

    /// Asset destroy: caid only, no apar at all.
    @Test
    internal func testAcfgDestroy() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = AssetConfigTransaction.destroy(
            sender: try Self.accountA(),
            assetID: Self.assetID,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "88a463616964ce01e1ab70a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863" +
            "b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415" +
            "bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a461636667",
            txID: "IMSM4LPJMOFDWLJZTOOQYG7G36GEMCEVDIW6Q6VES5UDIQTOZ5WA"
        )
    }

    // MARK: - AssetFreeze

    /// Freeze: afrz true is emitted as msgpack true (0xC3).
    @Test
    internal func testAfrzFreeze() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = AssetFreezeTransaction(
            sender: try Self.accountA(),
            assetID: Self.assetID,
            freezeAccount: try Self.accountB(),
            frozen: true,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "8aa46166727ac3a466616464c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0" +
            "a466616964ce01e1ab70a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b5" +
            "18a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc" +
            "02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a46166727a",
            txID: "GZONWS4EBD3Z2A2XFA7X7Y4CRSZLSUKAOM7N2W4DD7URCXPEHV6Q"
        )
    }

    /// Unfreeze: afrz false MUST be omitted entirely.
    @Test
    internal func testAfrzUnfreeze() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = AssetFreezeTransaction(
            sender: try Self.accountA(),
            assetID: Self.assetID,
            freezeAccount: try Self.accountB(),
            frozen: false,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a466616464c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a466616964ce" +
            "01e1ab70a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec8" +
            "10f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d4" +
            "0bd8e022605d7cbedbfef850793065291e151dc496a474797065a46166727a",
            txID: "TYB5WMLTC5DEDY4LR4NIGSB7FOTYCUR3LPKIH5CKUNO62DJ52J2Q"
        )
    }

    // MARK: - ApplicationCall

    /// Bare NoOp call: only apid beyond the header. apan=0 (NoOp) is omitted.
    @Test
    internal func testApplNoopMinimal() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.call(
            sender: try Self.accountA(),
            applicationID: Self.appID,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "88a461706964ce4c8d442fa3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863" +
            "b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415" +
            "bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a46170706c",
            txID: "UUWRZMIV3PLQL5IYTE3D4YICVAE2FFZFOFHHTVMTGQVMBUUEHP2Q"
        )
    }

    /// OptIn: apan=1 is emitted.
    @Test
    internal func testApplOptIn() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.optIn(
            sender: try Self.accountA(),
            applicationID: Self.appID,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a46170616e01a461706964ce4c8d442fa3666565cd03e8a2667633a367656eac746573746e65742d76312e30a2" +
            "6768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64" +
            "c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a46170706c",
            txID: "S2Y7H4SDVVT3T5I7VBNSRT76CRM4KBN2D3O5F6XDYEOTMLFT77KA"
        )
    }

    /// Application arguments, including an empty arg (which is a legitimate element of apaa and must NOT be
    /// dropped: omitempty applies to the array, not to its elements).
    @Test
    internal func testApplArgs() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.call(
            sender: try Self.accountA(),
            applicationID: Self.appID,
            appArguments: [Data("method".utf8), Data(), Data(repeating: 0xFF, count: 8)],
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a46170616193c4066d6574686f64c400c408ffffffffffffffffa461706964ce4c8d442fa3666565cd03e8a266" +
            "7633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac" +
            "20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef85079" +
            "3065291e151dc496a474797065a46170706c",
            txID: "VHXD7QU4LIW6OHVM7NZFAPZQ5Q3HPXFPEAJZTEOKCOGVP2Z4FGPQ"
        )
    }

    /// Foreign arrays: apat, apas, apfa all populated.
    @Test
    internal func testApplAccountsAssetsApps() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.call(
            sender: try Self.accountA(),
            applicationID: Self.appID,
            accounts: [try Self.accountB(), try Self.accountC()],
            foreignApps: [Self.foreignApp1, Self.foreignApp2],
            foreignAssets: [Self.assetID],
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "8ba46170617391ce01e1ab70a46170617492c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf2" +
            "4638b6c2d9e0c4207dcaddbc1753dee3199314c8c6992ae5911b573d729190cc266f40d153a9de81a46170666192" +
            "ce3ade68b1ce075bcd15a461706964ce4c8d442fa3666565cd03e8a2667633a367656eac746573746e65742d7631" +
            "2e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3" +
            "736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a4617070" +
            "6c",
            txID: "65WMNLQE42ESIRHP4LHP34ADL3UWQHQ7LFQE2WKVOHCTILZLZDBQ"
        )
    }

    /// Box reference on the CURRENT app. The caller writes appID 0 (or the app's own ID); the wire `i` slot is
    /// index 0 and is therefore omitted. Writing the raw app ID here is the defect.
    @Test
    internal func testApplBoxCurrentApp() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.call(
            sender: try Self.accountA(),
            applicationID: Self.appID,
            boxes: [(0, Data("counter".utf8))],
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a4617062789181a16ec407636f756e746572a461706964ce4c8d442fa3666565cd03e8a2667633a367656eac74" +
            "6573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e509" +
            "3a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496" +
            "a474797065a46170706c",
            txID: "4XGJWTVUAAAA6BIXBFUYFWOJH6JEK2Z6ZSXZGCQZCVODVDCI6OZQ"
        )
    }

    /// Box reference written as the app's OWN id. Still index 0 on the wire.
    @Test
    internal func testApplBoxSelfAppId() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.call(
            sender: try Self.accountA(),
            applicationID: Self.appID,
            boxes: [(Self.appID, Data("counter".utf8))],
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a4617062789181a16ec407636f756e746572a461706964ce4c8d442fa3666565cd03e8a2667633a367656eac74" +
            "6573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e509" +
            "3a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496" +
            "a474797065a46170706c",
            txID: "4XGJWTVUAAAA6BIXBFUYFWOJH6JEK2Z6ZSXZGCQZCVODVDCI6OZQ"
        )
    }

    /// Box references on foreign apps. apfa=[987654321, 123456789]; a box on 987654321 encodes i=1 and a box on
    /// 123456789 encodes i=2. The SDK writes the raw app id (a 4-byte uint32) instead of the small index.
    @Test
    internal func testApplBoxForeignApp() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.call(
            sender: try Self.accountA(),
            applicationID: Self.appID,
            foreignApps: [Self.foreignApp1, Self.foreignApp2],
            boxes: [
                (Self.foreignApp1, Data("alpha".utf8)),
                (Self.foreignApp2, Data("beta".utf8)),
                (0, Data("local".utf8))
            ],
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "8aa4617062789382a16901a16ec405616c70686182a16902a16ec4046265746181a16ec4056c6f63616ca4617066" +
            "6192ce3ade68b1ce075bcd15a461706964ce4c8d442fa3666565cd03e8a2667633a367656eac746573746e65742d" +
            "76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd04" +
            "1ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a461" +
            "70706c",
            txID: "NMWRFIHTN4LHLNETDTSSOAIPWPJINPOXSJLIHDWHQPPRXFC5CPLQ"
        )
    }

    /// The append path: the caller declares NO foreign apps and names a box on `foreignApp1`. The SDK must
    /// append the app to `apfa` and encode the box as `i: 1`. go-algorand's canonical form is identical to the
    /// caller having declared `apfa=[foreignApp1]` explicitly, so the golden bytes carry the same authority as
    /// every other vector in this suite (generated from the same go-algorand v5.0.1-stable semantics).
    /// Verified live against TestNet: the pre-change bytes were rejected with "tx.Boxes[0].Index is 987654321.
    /// Exceeds len(tx.ForeignApps)"; the appended form reaches balance application.
    @Test
    internal func testApplBoxAppendPath() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.call(
            sender: try Self.accountA(),
            applicationID: Self.appID,
            foreignApps: nil,
            boxes: [
                (Self.foreignApp1, Data("appended".utf8))
            ],
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        let encodedHex = try transaction.encode(groupID: nil).hexString
        let apbxRange = try #require(encodedHex.range(of: "a461706278"), "apbx must be present")
        let apfaRange = try #require(encodedHex.range(of: "a461706661"), "apfa must have been appended")
        let apbxSlice = encodedHex[apbxRange.lowerBound..<apfaRange.lowerBound]
        #expect(!apbxSlice.contains("ce3ade68b1"), "raw app id 987654321 must not appear inside apbx")

        try assertCanonical(
            transaction,
            encodesTo: "8aa4617062789182a16901a16ec408617070656e646564a46170666191ce3ade68b1a461706964ce4c8d442fa366" +
            "6565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb" +
            "0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbe" +
            "dbfef850793065291e151dc496a474797065a46170706c",
            txID: "VYD5X4ZFF6T5L67PBXFOOSGY2J56IRRZETOYMCTXHDMF74YY5DJA"
        )
    }

    /// Box reference with an empty name: `n` is dropped, leaving an empty map.
    @Test
    internal func testApplBoxEmptyName() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.call(
            sender: try Self.accountA(),
            applicationID: Self.appID,
            boxes: [(0, Data())],
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a4617062789180a461706964ce4c8d442fa3666565cd03e8a2667633a367656eac746573746e65742d76312e30" +
            "a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e" +
            "64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a46170706c",
            txID: "DUPVF6T3AUV7FHXABGWVV7JUU6SAVN6HUQ2UGVW6OOGQGPXTOLNQ"
        )
    }

    /// App creation: apid omitted (0), programs and both schemas present.
    @Test
    internal func testApplCreateWithSchemas() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.create(
            sender: try Self.accountA(),
            approvalProgram: try Self.approvalProgram(),
            clearStateProgram: try Self.clearStateProgram(),
            globalStateSchema: StateSchema(numUint: 2, numByteSlice: 3),
            localStateSchema: StateSchema(numUint: 1, numByteSlice: 1),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "8ba461706170c4030a8101a46170677382a36e627303a36e756902a461706c7382a36e627301a36e756901a46170" +
            "7375c4030a8101a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3" +
            "c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185" +
            "f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a46170706c",
            txID: "WGQH23OE47A5NBMZSA5YAHNIJ7E6HBPOUWYLJWC4FGMEZPBVAQ7Q"
        )
    }

    /// App creation with all-zero schemas: apgs/apls collapse to nothing and MUST be omitted entirely, not emitted
    /// as empty maps.
    @Test
    internal func testApplCreateZeroSchemas() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.create(
            sender: try Self.accountA(),
            approvalProgram: try Self.approvalProgram(),
            clearStateProgram: try Self.clearStateProgram(),
            globalStateSchema: StateSchema(numUint: 0, numByteSlice: 0),
            localStateSchema: StateSchema(numUint: 0, numByteSlice: 0),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a461706170c4030a8101a461707375c4030a8101a3666565cd03e8a2667633a367656eac746573746e65742d76" +
            "312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041b" +
            "a3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a46170" +
            "706c",
            txID: "P6RPQ3BPWXX6ZKET3ZS7BRUA5E37LTHS4JEEHV4J5QXDBFP645JQ"
        )
    }

    /// App creation with 3 extra pages (the v42 maximum is 7).
    @Test
    internal func testApplCreateExtraPages() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.create(
            sender: try Self.accountA(),
            approvalProgram: try Self.approvalProgram(),
            clearStateProgram: try Self.clearStateProgram(),
            globalStateSchema: StateSchema(numUint: 1, numByteSlice: 0),
            localStateSchema: StateSchema(numUint: 0, numByteSlice: 0),
            extraPages: 3,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "8ba461706170c4030a8101a46170657003a46170677381a36e756901a461707375c4030a8101a3666565cd03e8a2" +
            "667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7" +
            "ac20dec62f7f70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850" +
            "793065291e151dc496a474797065a46170706c",
            txID: "O5BDPWNVKXRTKMS7VZMRMG6T7QKM6TCFKX33YIDHK7IR24P7EOJA"
        )
    }

    /// extra_pages=0 MUST be omitted.
    @Test
    internal func testApplExtraPagesZero() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.create(
            sender: try Self.accountA(),
            approvalProgram: try Self.approvalProgram(),
            clearStateProgram: try Self.clearStateProgram(),
            globalStateSchema: StateSchema(numUint: 1, numByteSlice: 0),
            localStateSchema: StateSchema(numUint: 0, numByteSlice: 0),
            extraPages: 0,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "8aa461706170c4030a8101a46170677381a36e756901a461707375c4030a8101a3666565cd03e8a2667633a36765" +
            "6eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f" +
            "70e5093a22a26c76cd041ba3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e15" +
            "1dc496a474797065a46170706c",
            txID: "IVNAZH66HBY5T4XCUGQELZ63NZOMJDFA25NBUP35XLIPAXZBDZ3Q"
        )
    }

    /// Delete application: apan=5.
    @Test
    internal func testApplDelete() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.delete(
            sender: try Self.accountA(),
            applicationID: Self.appID,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )

        try assertCanonical(
            transaction,
            encodesTo: "89a46170616e05a461706964ce4c8d442fa3666565cd03e8a2667633a367656eac746573746e65742d76312e30a2" +
            "6768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3736e64" +
            "c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a46170706c",
            txID: "IGSEZY2GMVMTBJY2JPG2ZA3P5JMQZRZQ7ZXF7NSR46LSGPTWLVJQ"
        )
    }

    /// Every appl field at once: args, accounts, foreign apps/assets, boxes on both a foreign app and the current
    /// app, extra pages, both programs, both schemas, note, lease and rekey.
    @Test
    internal func testApplKitchenSink() throws {
        let genesisHash = try Self.genesisHash()
        let transaction = ApplicationCallTransaction.create(
            sender: try Self.accountA(),
            approvalProgram: try Self.approvalProgram(),
            clearStateProgram: try Self.clearStateProgram(),
            globalStateSchema: StateSchema(numUint: 4, numByteSlice: 5),
            localStateSchema: StateSchema(numUint: 6, numByteSlice: 7),
            appArguments: [Data("arg0".utf8), Data("arg1".utf8)],
            accounts: [try Self.accountB()],
            foreignApps: [Self.foreignApp1],
            foreignAssets: [Self.assetID],
            boxes: [(Self.foreignApp1, Data("foreign-box".utf8)), (0, Data("own-box".utf8))],
            extraPages: 1,
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash,
            note: try Self.noteHello(),
            lease: try Self.leaseNonZero(),
            rekeyTo: try Self.accountC()
        )

        try assertCanonical(
            transaction,
            encodesTo: "de0014a46170616192c40461726730c40461726731a461706170c4030a8101a46170617391ce01e1ab70a4617061" +
            "7491c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a4617062789282a16901" +
            "a16ec40b666f726569676e2d626f7881a16ec4076f776e2d626f78a46170657001a46170666191ce3ade68b1a461" +
            "70677382a36e627305a36e756904a461706c7382a36e627307a36e756906a461707375c4030a8101a3666565cd03" +
            "e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f0" +
            "59a7ac20dec62f7f70e5093a22a26c76cd041ba26c78c4200102030405060708090a0b0c0d0e0f10111213141516" +
            "1718191a1b1c1d1e1f20a46e6f7465c41468656c6c6f2073776966742d616c676f72616e64a572656b6579c4207d" +
            "caddbc1753dee3199314c8c6992ae5911b573d729190cc266f40d153a9de81a3736e64c420d4eb7415bc02f185f0" +
            "32d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a46170706c",
            txID: "2OYITAGWYZ5JGALRDTBMFHX7JM6AEWTFDEEL6EG5PYTAM7QLTFBQ"
        )
    }

    // MARK: - Atomic groups and the grouped-vs-ungrouped transaction ID

    /// The group ID for the canonical 2-payment group. Computed as
    /// SHA512-256("TG" + msgpack({"txlist": [txid0, txid1]})).
    internal static let groupIDHex = "2e17dd6e388e7b5a34dc844cf3555711687f06b9633796ccaf082239247fd899"

    internal func makeGroupTransactions() throws -> [PaymentTransaction] {
        let genesisHash = try Self.genesisHash()
        let first = PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(1_000_000),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )
        let second = PaymentTransaction(
            sender: try Self.accountB(),
            receiver: try Self.accountA(),
            amount: MicroAlgos(500_000),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: genesisHash
        )
        return [first, second]
    }

    /// The group ID must be exactly this value, not merely 32 bytes long.
    @Test
    internal func testGroupIDIsExactlyTheGoldenValue() throws {
        let group = try AtomicTransactionGroup(transactions: try makeGroupTransactions())
        #expect(group.groupID.hexString == Self.groupIDHex)
    }

    /// Building the same group twice must produce identical bytes, not merely two 32-byte values.
    @Test
    internal func testGroupIDIsStableAcrossConstruction() throws {
        let first = try AtomicTransactionGroup(transactions: try makeGroupTransactions())
        let second = try AtomicTransactionGroup(transactions: try makeGroupTransactions())
        #expect(first.groupID == second.groupID)
        #expect(first.groupID.hexString == Self.groupIDHex)
    }

    /// First transaction of the group, encoded WITH `grp`.
    @Test
    internal func testGroupedTransactionZeroEncoding() throws {
        let group = try AtomicTransactionGroup(transactions: try makeGroupTransactions())
        let transactions = try makeGroupTransactions()
        try assertCanonical(
            transactions[0],
            groupID: group.groupID,
            encodesTo: "8aa3616d74ce000f4240a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b5" +
            "18a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a3677270c4202e17dd6e388e7b5a34dc84" +
            "4cf3555711687f06b9633796ccaf082239247fd899a26c76cd041ba3726376c4208485b1e921ad04a14459050fd1" +
            "ebbbde38183318e8baf1961cf24638b6c2d9e0a3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfe" +
            "f850793065291e151dc496a474797065a3706179",
            txID: "3ZFBH32KQJVFCXLXVRCONWKYXL5R5EENIRHKURR3LFL4UGPD3CFQ"
        )
    }

    /// Second transaction of the group, encoded WITH `grp`.
    @Test
    internal func testGroupedTransactionOneEncoding() throws {
        let group = try AtomicTransactionGroup(transactions: try makeGroupTransactions())
        let transactions = try makeGroupTransactions()
        try assertCanonical(
            transactions[1],
            groupID: group.groupID,
            encodesTo: "8aa3616d74ce0007a120a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b5" +
            "18a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a3677270c4202e17dd6e388e7b5a34dc84" +
            "4cf3555711687f06b9633796ccaf082239247fd899a26c76cd041ba3726376c420d4eb7415bc02f185f032d40bd8" +
            "e022605d7cbedbfef850793065291e151dc496a3736e64c4208485b1e921ad04a14459050fd1ebbbde38183318e8" +
            "baf1961cf24638b6c2d9e0a474797065a3706179",
            txID: "TSZ22F24UXDJMCMFDZBDDKJOI7PM7BUCLAUBTDTBXNGPVKQ7RVHQ"
        )
    }

    /// The same transaction encoded WITHOUT `grp` has a DIFFERENT transaction ID. This pair is
    /// the whole point of the group-ID defect: a grouped transaction's on-chain ID is the hash of
    /// the grouped encoding, so anything that re-encodes with a nil group ID reports an ID that
    /// does not exist on chain.
    @Test
    internal func testGroupedAndUngroupedTransactionIDsDiffer() throws {
        let transactions = try makeGroupTransactions()
        let group = try AtomicTransactionGroup(transactions: transactions)

        let ungrouped = try transactions[0].encode(groupID: nil)
        let grouped = try transactions[0].encode(groupID: group.groupID)

        #expect(
            Self.transactionID(forEncoded: ungrouped) == "O5CHKYIB3T7YBA4KATYKNGWU5AB3NTN2TZ2E2IJUIZXRMNPINM2Q"
        )
        #expect(
            Self.transactionID(forEncoded: grouped) == "3ZFBH32KQJVFCXLXVRCONWKYXL5R5EENIRHKURR3LFL4UGPD3CFQ"
        )
        #expect(Self.transactionID(forEncoded: ungrouped) != Self.transactionID(forEncoded: grouped))
    }

    /// A signed grouped transaction must report the GROUPED transaction ID. `SignedTransaction`
    /// carries the group ID, so it has everything it needs; forwarding to `Transaction.id()`
    /// throws that information away and yields the ungrouped ID.
    @Test
    internal func testSignedGroupedTransactionReportsGroupedID() throws {
        let transactions = try makeGroupTransactions()
        let group = try AtomicTransactionGroup(transactions: transactions)
        let account = try Account()
        let signed = try SignedTransaction.sign(
            transactions[0],
            with: account,
            groupID: group.groupID
        )

        let transactionID = try signed.id()
        #expect(transactionID == "3ZFBH32KQJVFCXLXVRCONWKYXL5R5EENIRHKURR3LFL4UGPD3CFQ")
    }

    // MARK: - Signed transaction envelopes

    /// The unsigned payment that the signed-envelope vectors wrap.
    internal func makeEnvelopeTransaction() throws -> PaymentTransaction {
        PaymentTransaction(
            sender: try Self.accountA(),
            receiver: try Self.accountB(),
            amount: MicroAlgos(1_000_000),
            fee: MicroAlgos(1000),
            firstValid: 51,
            lastValid: 1051,
            genesisID: Self.genesisID,
            genesisHash: try Self.genesisHash()
        )
    }

    /// Ed25519-only envelope: a 2-key map {sig, txn}.
    ///
    /// The signature bytes cannot be asserted on Darwin. Apple's CryptoKit randomizes the Ed25519
    /// nonce: signing one message with one key eight times produces eight distinct signatures
    /// (measured, not assumed). swift-crypto's BoringSSL backend, used on Linux and Windows, is
    /// RFC 8032 deterministic -- `ED25519_sign` derives the nonce as SHA512(prefix || message) --
    /// so there the signature IS reproducible and `signatureHex` below is the exact expected value.
    /// The portable assertion is therefore: the envelope's fixed regions are exact, the signature
    /// verifies, and the whole thing is the right length.
    internal static let signedEnvelopeUnsignedTxnHex =
        "89a3616d74ce000f4240a3666565cd03e8a2667633a367656eac746573746e65742d76312e30a26768c4204863b518a4" +
        "b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a26c76cd041ba3726376c4208485b1e921ad04a144" +
        "59050fd1ebbbde38183318e8baf1961cf24638b6c2d9e0a3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbe" +
        "dbfef850793065291e151dc496a474797065a3706179"
    internal static let signedEnvelopeSignatureHex =
        "8dfbd7887bd7eedb009e7b6c112c1751013db29c33c3bf48ea13effc061bd1712f00c9d9580d9820245a828a56a387a0" +
        "395b590f26a4e43edfc00f240bf2f609"
    internal static let signedEnvelopeHex =
        "82a3736967c4408dfbd7887bd7eedb009e7b6c112c1751013db29c33c3bf48ea13effc061bd1712f00c9d9580d982024" +
        "5a828a56a387a0395b590f26a4e43edfc00f240bf2f609a374786e89a3616d74ce000f4240a3666565cd03e8a2667633" +
        "a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f" +
        "7f70e5093a22a26c76cd041ba3726376c4208485b1e921ad04a14459050fd1ebbbde38183318e8baf1961cf24638b6c2" +
        "d9e0a3736e64c420d4eb7415bc02f185f032d40bd8e022605d7cbedbfef850793065291e151dc496a474797065a37061" +
        "79"

    @Test
    internal func testSignedEnvelopeStructure() throws {
        let transaction = try makeEnvelopeTransaction()
        // The sender signs for itself. Any other account would be a rekeyed signer, and the
        // envelope would (correctly) carry `sgnr` as a third key.
        let seed = try hexData("14a16b7d74ba2c495533d743658ee19bc27300ce302a4f19f3bb766a3c8cb02e")
        let account = try Account(privateKey: seed)
        #expect(account.address == transaction.sender)
        let signed = try SignedTransaction.sign(transaction, with: account)
        let encoded = try signed.encode()

        // 0x82 fixmap(2), "sig", bin8(64)
        #expect(encoded.prefix(7).hexString == "82a3736967c440")
        #expect(encoded.count == 241)

        // The embedded txn must be byte-identical to the standalone encoding.
        let unsigned = try transaction.encode(groupID: nil)
        #expect(unsigned.hexString == Self.signedEnvelopeUnsignedTxnHex)
        #expect(encoded.suffix(unsigned.count + 4).hexString == "a374786e" + unsigned.hexString)

        // The signature must verify over "TX" + encoded, whatever its bytes.
        #expect(account.verify(signature: signed.signature, for: Data("TX".utf8) + unsigned))
    }

    /// On a deterministic Ed25519 backend the whole envelope is byte-exact. This test is a no-op
    /// on Darwin, where CryptoKit's randomized nonce makes the signature unreproducible.
    @Test(
        .enabled(
            if: CanonicalEncodingTests.ed25519SignaturesAreDeterministic,
            "CryptoKit randomizes the Ed25519 nonce; signature bytes are not reproducible on Darwin."
        )
    )
    internal func testSignedEnvelopeIsByteExactOnDeterministicBackends() throws {
        let transaction = try makeEnvelopeTransaction()
        let seed = try hexData("14a16b7d74ba2c495533d743658ee19bc27300ce302a4f19f3bb766a3c8cb02e")
        let account = try Account(privateKey: seed)
        let signed = try SignedTransaction.sign(transaction, with: account)
        let encoded = try signed.encode()

        #expect(signed.signature.hexString == Self.signedEnvelopeSignatureHex)
        #expect(encoded.hexString == Self.signedEnvelopeHex)
    }
}

// MARK: - Hex helpers

internal enum CanonicalVectorError: Error, CustomStringConvertible {
    case invalidHex(String)

    internal var description: String {
        switch self {
        case .invalidHex(let value): return "Not a valid hex string: \(value)"
        }
    }
}

/// Decodes a lowercase hex string into `Data`, throwing rather than force-unwrapping.
internal func hexData(_ string: String) throws -> Data {
    guard string.count % 2 == 0 else {
        throw CanonicalVectorError.invalidHex(string)
    }

    var bytes = [UInt8]()
    bytes.reserveCapacity(string.count / 2)

    var index = string.startIndex
    while index < string.endIndex {
        let next = string.index(index, offsetBy: 2)
        guard let byte = UInt8(string[index..<next], radix: 16) else {
            throw CanonicalVectorError.invalidHex(string)
        }
        bytes.append(byte)
        index = next
    }

    return Data(bytes)
}

extension Data {
    /// Lowercase hex, so failures print a diff a human can read.
    internal var hexString: String {
        map { String(format: "%02x", $0) }.joined()
    }

    /// Whether this data contains `subsequence` anywhere.
    internal func containsSubsequence(_ subsequence: Data) -> Bool {
        guard !subsequence.isEmpty, subsequence.count <= count else {
            return false
        }

        let selfBytes = Array(self)
        let needle = Array(subsequence)
        for start in 0...(selfBytes.count - needle.count) where
            Array(selfBytes[start..<(start + needle.count)]) == needle {
            return true
        }
        return false
    }
}
